
# build docs from docstrings and markdown-file in folder docs
# publish them as github pages
#
#note for myself
#
# Do not forget to set git branch `gh-pages` as source for github pages.
# This branch auto-updated by `mkdocs gh-deploy`
#
name: docs
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    env:
      PRIMARY_PYTHON_VERSION: '3.12'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION  }}
      - run: |
          pip install uv
          uv pip install ghp-import -r requirements.dev.txt --python=${{ env.PRIMARY_PYTHON_VERSION }}

      - run: |
          ./scripts/build-docs.sh
          ghp-import --no-jekyll --push --force site

      - name: Restore allure directory
        run: |
          git fetch origin
          git checkout gh-pages
          mkdir -p allure
          mv gh-pages/allure/* allure/
          git add allure/
          git commit -m "Restore allure directory"
          git push origin gh-pages